### POST USER
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "leonan teste 2",
  "email": "9T5Yt22@example.com",
  "password": "123456"
}

### Authenticate
POST http://localhost:3333/users/sessions
Content-Type: application/json

{
  "email": "9T5Yt@example.com",
  "password": "123456"
}

### Profile
GET http://localhost:3333/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiN2Q3ZGU0OS04MzkxLTQ0YjgtYWZjZC05OTZhMDhjYjg3YWMiLCJpYXQiOjE3NDY2NzU4Nzh9.fG4wZ4Im1eJFjmLT2Z1iyPiA-6Cj-Tk78_jRoOvUdhA