### POST USER
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "leonan teste 2",
  "email": "9T5Yt22@example.com",
  "password": "123456"
}

### Authenticate
POST http://localhost:3333/sessions
Content-Type: application/json

{
  # "email": "9T5Yt@example.com",
  "password": "123456"
}

### Profile
GET http://localhost:3333/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiN2Q3ZGU0OS04MzkxLTQ0YjgtYWZjZC05OTZhMDhjYjg3YWMiLCJpYXQiOjE3NDY1MDM4Mzh9.7z1hOLlNR8TCliWGI9RjBkLtT1FjTth5HQLc8rYWI38