name: Run e2e tests

on: [pull_request]

jobs:
  run-e2e-tests:
  
    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: api-solid-pg

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
        env: 
          JWT_SECRET: test_secret
          DATABASE_URL: "postgres://docker:docker@localhost:5432/api-solid-pg?schema=public"

      - run: pnpm i --frozen-lockfile
      - run: pnpm test:e2e